FROM alicevision_base:latest
RUN apt-get update -y && \
  apt-get dist-upgrade -y && \
  apt-get install -y exiftool vim python3
COPY scripts /scripts
RUN chmod +x /scripts/genPoseSFM.sh
ENV LD_LIBRARY_PATH="/opt/AliceVision_install/lib:${LD_LIBRARY_PATH}"
ENV PATH="/opt/AliceVision_install/bin:${PATH}"
ENV MAKE="Fujinon"
ENV MODEL="Fujinon 12.5mm 2/3inch C mount Lens"
ENV FOCAL_LENGTH="12.5"
ENV NUM_CAMS="72"
RUN echo "${MAKE};${MODEL};${FOCAL_LENGTH}" >> /opt/AliceVision_bundle/share/aliceVision/cameraSensors.db

