FROM alicevision_base:latest
RUN apt-get update -y && \
  apt-get dist-upgrade -y && \
  apt-get install -y exiftool vim python3
RUN chmod +x ${AV_DEV}/scripts/genPoseSFM.sh
ENV LD_LIBRARY_PATH="${AV_INSTALL}/lib:${LD_LIBRARY_PATH}"
ENV PATH="${AV_INSTALL}/bin:${PATH}"
ENV SVR_CAM_MAKE="Fujinon"
ENV SVR_CAM_MODEL="Fujinon 12.5mm 2/3inch C mount Lens"
ENV SVR_CAM_FOCAL_LENGTH="12.5"
